name: Check Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Eslint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install module...
      run: npm ci
    
    - name: Check with Eslint...
      run: npm run lint
  Mocha:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install module...
      run: npm install

    - name: Build...
      run: npm run build

    - name: Running test with coverage...
      run: npm run coverage
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}

    - name: Send to SonarCloud 
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: /github/workspace/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
 