name: Check Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Eslint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install module...
      run: npm ci
    
    - name: Check with Eslint...
      run: npm run lint
  Mocha:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install module...
      run: npm ci

    - name: Build...
      run: npm run build

    - name: Running test with coverage...
      run: npm run coverage
      env:
        API_TEST: ${{ secrets.API_TEST }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        SECRET_KEY_REFRESH: ${{ secrets.SECRET_KEY_REFRESH }}
        COOKER_DEFAUT_EMAIL: ${{ secrets.COOKER_DEFAUT_EMAIL }}
        COOKER_DEFAUT_PASSWORD: ${{ secrets.COOKER_DEFAUT_PASSWORD }}
        EMAIL_SUPPORT: ${{ secrets.EMAIL_SUPPORT }}
        NODE_MAIL_TEST_MODE: ${{ secrets.NODE_MAIL_TEST_MODE }}
        SECRET_KEY_REST_TEST: ${{ secrets.SECRET_KEY_REST_TEST }}
        HOST_SMTP_URL_TEST: ${{ secrets.HOST_SMTP_URL_TEST }}
        SMTP_PORT_TEST: ${{ secrets.SMTP_PORT_TEST }}
        EMAIL_SUPPORT_TEST: ${{ secrets.EMAIL_SUPPORT_TEST }}
        PASSWORD_SUPPORT_TEST: ${{ secrets.PASSWORD_SUPPORT_TEST }}

    - name: Send to SonarCloud 
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: /github/workspace/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
 